INSERT INTO canciones (título, artista, categoría) VALUES
('Sin ti', 'Luis Miguel', 'Violín Solo'),
('Fly Me to the Moon', 'Frank Sinatra', 'Violín Solo'),
('Sarà perché ti amo', 'Ricchi e Poveri', 'Violín Solo'),
('Trío Bolero (Sabor a mí, Bésame mucho, Solamente una vez)', 'Varios', 'Violín Solo'),
('Medley (La vie en Rose, Beyond the sea, Blue Moon)', 'Varios', 'Violín Solo'),
('Chiquitita', 'ABBA', 'Violín Solo'),
('Viva la Vida', 'Coldplay', 'Violín Solo'),
('Die With a Smile', 'Lady Gaga & Bruno Mars', 'Violín Solo'),
('Flowers', 'Miley Cyrus', 'Violín Solo'),
('The Girl from Ipanema', 'Antônio Carlos Jobim', 'Violín Solo'),
('Yellow', 'Coldplay', 'Violín Solo'),
('A Thousand Years', 'Christina Perri', 'Violín Solo'),
('Fix You', 'Coldplay', 'Violín Solo'),
('Until I Found You', 'Stephen Sanchez', 'Violín Solo'),
('Somewhere Only We Know', 'Keane', 'Violín Solo'),
('Photograph', 'Ed Sheeran', 'Violín Solo'),
('A Sky Full of Stars', 'Coldplay', 'Violín Solo'),
('Golden Hour', 'JVKE', 'Violín Solo'),
('Just the Way You Are', 'Bruno Mars', 'Violín Solo'),
('All of Me', 'John Legend', 'Violín Solo'),
('Merry Go Round of Life', 'Joe Hisaishi', 'Violín Solo'),
('Por una Cabeza', 'Carlos Gardel', 'Violín Solo'),
('Close to You', 'The Carpenters', 'Violín Solo'),
('O Sole Mio', 'Eduardo di Capua', 'Violín Solo'),
('Lover', 'Taylor Swift', 'Violín Solo'),
('This Will Be', 'Natalie Cole', 'Violín Solo'),
('City of Stars', 'La La Land', 'Violín Solo'),
('Turning Page', 'Sleeping At Last', 'Violín Solo'),
('Mi Corazón Encantado', 'Dragon Ball GT', 'Violín Solo'),
('Sign of the Times', 'Harry Styles', 'Violín Solo'),
('Firework', 'Katy Perry', 'Violín Solo'),
('One and Only', 'Adele', 'Violín Solo'),
('Always Remember Us This Way', 'Lady Gaga', 'Violín Solo'),
('Hasta Mi Final', 'Il Divo', 'Violín Solo'),
('Married Life', 'Up (Película)', 'Violín Solo'),
('Marry You', 'Bruno Mars', 'Violín Solo'),
('Thinking Out Loud', 'Ed Sheeran', 'Violín Solo'),
('Por Ti Volaré', 'Andrea Bocelli', 'Violín Solo'),
('Can''t Take My Eyes Off You', 'Frankie Valli', 'Violín Solo'),
('Te regalo', 'Carla Morrison', 'Violín Solo'),
('Contigo', 'Los Panchos', 'Violín Solo');
